### ISSUE TITLE
groovy build

### ISSUE THREAD

**Issue by stsp** [jwt27/build-gcc#17]
Would be nice to enable groovy
build on LP. Also bionic build seems
to have failed.

**Comment by stsp** [comment]
It failed on arm64 though. :)

**Comment by jwt27** [comment]
Thanks for the reminder, I briefly looked into it yesterday but wasn't sure if it was out yet (it doesn't help that googling for "ubuntu groovy" only returns results for Apache Groovy...)

I did notice the failed arm64 build.  The same error happened the other day during a test build on MacOS, but it's no longer happening now, so it seems to be a spurious issue.  I disabled arm64 builds for now to save space on LP, I don't think it sees much use anyway.

**Comment by stsp** [comment]
One day we'll port dosemu2 on arm64...
But as of today - yes, not much of a use.
As for groovy - its not out at all (will be
in october), but the build works already,
so I'd like to switch them on for my packages.

**Comment by jwt27** [comment]
Groovy PPA is building now: https://launchpad.net/~jwt27/+archive/ubuntu/djgpp-toolchain/+build/19268446

Seems i386 support has been dropped from the latest Ubuntu releases so that will save some space (right now it's at 1.6/2.0GB).  I suppose we can re-enable arm64 at some point, let me know when you (or anyone else) need it.

**Comment by stsp** [comment]
Not soon... :)

Thanks for the build, I'll let you know
in case of any failures on my pkgs.
